### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by DimEvil**
Darwin Core Mapping up to date

### CODE REVIEW

**Comment by peterdesmet** [comment]
Great work! Here are the last things to change:
- [x] bibliographicCitation: Remove. Guidelines how to cite a record should be defined and standardized by GBIF, which are also in the perfect place to allow this technically. Providing our own guidelines would only complicate things.
- [x] institutionCode: Use `Diveboard`, not `www.diveboard.com`.
- [x] ownerInstitutionCode: Use `Diveboard`, not `www.diveboard.com`.
- [x] eventDate: Format as `2005-07-25T00:00:00Z`, not `2005-07-25 00:00:00`. Technically we should use local time zone (not `Z`), but that might be hard to do.
- [x] verbatimLocality: Use `locality, municipality` (as one would write an address), not `municipality / locality`.
- [x] taxonID: Use URL `http://eol.org/pages/ID`
- [x] nameAccordingToID: Remove.

**Comment by peterdesmet** [comment]
Resolved some conflicts. @DimEvil, see comment above for last 7 fields to update. :metal:

**Comment by DimEvil** [comment]
I m confused, i thought last time we had to change from DIVEBOARD to www.diveboard.com, but ok, i proposed to chenge again! :8ball:

**Comment by DimEvil** [comment]
it s done!

**Comment by DimEvil** [comment]
http://lifewatchinbo.github.io/torque/?user=dimitri&table=diveboard&column=eventdate
Dataset is published and off course moved into torque.

**Pull request merged**
